  /productos:
    get:
      summary: Obtener la lista de productos
      description: Obtener la lista de productos
      responses:
        '200':
          description: éxito
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PRODUCTO'
                  
    post:
      summary: Crea a un productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PRODUCTO'

      responses:
        '201':
          description: Created Crea a un productos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PRODUCTO'
                  

  /productos/{id_Producto}:
    get:
      summary: Obtener los datos de un productos
      parameters:
        - name: id_Producto
          in: path
          description: id de un productos
          required: true
          schema:
            type: string
            
      responses:
        '201':
          description: Crea a un productos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PRODUCTO'
                
    delete:
      summary: Elimina los datos de un productos
      parameters:
        - name: id_Producto
          in: path
          description: id de un productos
          required: true
          schema:
            type: string
            
      responses:
        '200':
          description: Eliminacion con exito
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PRODUCTO'
                
    put:
      summary: Acyualiza a un productos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PRODUCTO'
      parameters:
        - name: id_Producto
          in: path
          description: id de un productos
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Created Crea a un productos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PRODUCTO'